### ISSUE TITLE
Can't publish plugin

### ISSUE THREAD

**Issue by iTanzhao** [MscrmTools/XrmToolBox#1129]
I have developed a plugin which has been uploaded to nuget (https://www.nuget.org/packages/EntityAccessManagement/1.2022.1).

I don't know where I made a mistake that prevented it from publishing.

![image](https://user-images.githubusercontent.com/52996377/158360556-db62a850-adb0-4bd5-9485-c34c7fa3fb20.png)

**Comment by BetimBeja** [comment]
![image](https://user-images.githubusercontent.com/11160171/158361291-c6d97ee9-e59c-436d-bdb2-558413964d55.png)
Version 1.0.0 published one hour ago doesn't have XrmToolBox as a dependency, probably it is a caching problem... if you wait a while it should work.

**Comment by BetimBeja** [comment]
![image](https://user-images.githubusercontent.com/11160171/158362213-973e6a72-4bc5-4440-ae83-76bec058e1b9.png)
Also make sure that the version of your NuGet Package is aligned to the version of your assembly... it is a requirement for tools!

![image](https://user-images.githubusercontent.com/11160171/158362691-8c8842ee-043a-4636-a628-b25421fb6c7f.png)

**Comment by iTanzhao** [comment]
Thanks a lot for your help, but I still can't find my plugin...


![image](https://user-images.githubusercontent.com/52996377/158364333-c0d4afa2-c16b-4cab-bfc5-da0e24d3993f.png)
![image](https://user-images.githubusercontent.com/52996377/158364524-c035d375-28d0-42b2-ae2c-6a8b32ace6ea.png)
![image](https://user-images.githubusercontent.com/52996377/158364702-cc42b573-50b7-44d4-b6d5-48ed74b65fa9.png)

**Comment by BetimBeja** [comment]
I still see 1.2022.1 as the last published version, which contains you tool assembly with version 1.0.0.0, this will not get approved by @MscrmTools (Tanguy) unless you fix it. After you submit your tool it is manually tested and approved by Tanguy.
![image](https://user-images.githubusercontent.com/11160171/158366490-acfba330-d6b4-4ddf-b4c5-1521110b5d58.png)

**Comment by BetimBeja** [comment]
ps. I have manually installed your plugin on my computer, that's why I published a screenshot with the tool included.

**Comment by BetimBeja** [comment]
Just follow these instructions https://www.xrmtoolbox.com/documentation/for-developers/deploy-your-plugin-in-plugins-store/
And I would suggest you un-list the previous versions from NuGet so that only compliant versions are publicly available.

**Comment by MscrmTools** [comment]
Please unlist first versions of your Nuget package that does not contain the dependency to XrmToolBox information.
Then you should be able to register your plugin. 
But as said @BetimBeja, please ensure your assembly version and Nuget package version match

**Comment by iTanzhao** [comment]
Hi @MscrmTools  and @BetimBeja ,
Thanks to your suggestions, I have successfully registered my plugin (https://www.xrmtoolbox.com/plugins/EntityAccessManagement/).

Thanks.

**Comment by MscrmTools** [comment]
@iTanzhao I rejected your tool because you did not fix the version of your assembly.

**Comment by iTanzhao** [comment]
Hi @MscrmTools ，

I didn't understand how to fix the 1.0.0 version, I re-uploaded the nuget package, and it was prompted that it could not be uploaded.

![image](https://user-images.githubusercontent.com/52996377/158396465-ed25728d-1781-4671-a251-cc88a02b2377.png)

**Comment by iTanzhao** [comment]
@MscrmTools  
I have now released version 1.2022.3.1

https://www.nuget.org/packages/EntityAccessManagement/1.2022.3.1

**Comment by MscrmTools** [comment]
Your assembly is still versionned as 1.0.0.0
![image](https://user-images.githubusercontent.com/10774317/158405658-5d2c95a1-877a-4281-8600-cfa6f6ce9cbe.png)

**Comment by iTanzhao** [comment]
I understand, even if the version of the DLL file should be the same as the version of the nuget package, right?

I have now released version 1.2022.4 (https://www.nuget.org/packages/EntityAccessManagement/1.2022.4).

**Comment by MscrmTools** [comment]
Ok, it's validated! 
Please do not forget to always have the same version for your future updates between Assembly and Nuget package
