### ISSUE TITLE
Toolbox will not load

### ISSUE THREAD

**Issue by Hightower1** [MscrmTools/XrmToolBox#748]
After attempting to uninstall a plugin the whole toolbox seemed to crash. I get the error below then nothing appears. I can't go to settings or plugin store. I tried deleting the app from my computer and reinstalling it but that didn't fix it either. Any help would be appreciated even if it's starting over with new connections. 

![image](https://user-images.githubusercontent.com/37645475/38686054-0a528404-3e39-11e8-9d45-c45a57af40de.png)

![image](https://user-images.githubusercontent.com/37645475/38686059-0feca322-3e39-11e8-96fd-65f64792750e.png)

**Comment by MscrmTools** [comment]
In these conditions, try to find a file update.xml or delete.xml where xrmtoolbox is located and delete it.
That should solve the issue

**Comment by Hightower1** [comment]
That file does not exist in my folder. I did notice that on new extract from zip there is a plugins folder. 
![image](https://user-images.githubusercontent.com/37645475/38687925-76da9cc0-3e3d-11e8-8dd4-0a675e0067c4.png)

After i try to launch it the plugins folder is gone. 
![image](https://user-images.githubusercontent.com/37645475/38688023-ad3fe5ae-3e3d-11e8-9db6-db59bfa66d19.png)

**Comment by MscrmTools** [comment]
The first original error message cannot occur on a new XrmToolBox installation.
What is the problem after a réinstallation?

**Comment by Hightower1** [comment]
The problem was happening this morning so i removed the folder from my machine and re-downloaded the zip file from your site. After unblocking the zip and extracting the folders i am still getting that error. This is when I noticed that the Plugins Zip was disappearing. It appears it's still hooked into the original installation even though it's all been removed.

**Comment by MscrmTools** [comment]
The plugins.zip is normal. It’s my plugins package that is extracted the first time you run the application.

If you still have issues after reinstalling, then you have to clear the folder c:\users\yourlogin\appdata\roaming\mscrmtools\xrmtoolbox\plugins
You will need to download them again from plugins store (some of them are not available in plugins store btw)

**Comment by Hightower1** [comment]
Thank you

**Comment by rappen** [comment]
More tips around XTB files and storage :)
https://youtu.be/_nS5tnYM8lk

**Comment by bwmodular** [comment]
Really useful video thanks!
